### ISSUE TITLE
Docker images failing with "uninitialized constant Yajl::Encoder" 

### ISSUE THREAD

**Issue by matthewmodestino** [fluent/fluentd-docker-image#101]
Hi team, 

I have been working on building my own fluentd docker image from the debian 0.12 images (https://github.com/fluent/fluentd-docker-image/tree/master/v0.12/debian, to be exact) and had it working perfectly until i rebuilt my docker image with the .14 image this afternoon. (https://github.com/fluent/fluentd-docker-image/tree/master/v0.14/debian)

```
......
 && gem install oj -v 2.18.3 \
 && gem install json -v 2.1.0 \
 && gem install fluentd -v 0.14.22.rc1 \
&& gem install fluent-plugin-record-reformer \
&& gem install fluent-plugin-splunkhec \
&& gem install fluent-plugin-kubernetes_metadata_filter \
&& gem install ffi \
&& gem install fluent-plugin-systemd -v 0.0.8 \
......
```

Now the docker images fail to start with: 

```2017-10-20 23:55:11 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
/var/lib/gems/2.3.0/gems/yajl-ruby-1.3.0/lib/yajl/json_gem/encoding.rb:5:in `<top (required)>': uninitialized constant Yajl::Encoder (NameError)
Did you mean?  EncodingError
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/yajl-ruby-1.3.0/lib/yajl/json_gem.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
	from /var/lib/gems/2.3.0/gems/fluent-plugin-splunkhec-1.4/lib/fluent/plugin/out_splunkhec.rb:3:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/registry.rb:102:in `block in search'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/registry.rb:99:in `each'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/registry.rb:99:in `search'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/registry.rb:44:in `lookup'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/plugin.rb:146:in `new_impl'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/plugin.rb:104:in `new_output'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/agent.rb:128:in `add_match'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/agent.rb:72:in `block in configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/agent.rb:64:in `each'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/agent.rb:64:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/root_agent.rb:112:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/engine.rb:131:in `configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/engine.rb:96:in `run_configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/supervisor.rb:770:in `run_configure'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/supervisor.rb:553:in `dry_run'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/supervisor.rb:571:in `supervise'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/supervisor.rb:476:in `run_supervisor'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.3.0/gems/fluentd-0.14.22.rc1/bin/fluentd:5:in `<top (required)>'
	from /usr/local/bin/fluentd:22:in `load'
	from /usr/local/bin/fluentd:22:in `<main>'
```

Please advise.

**Comment by matthewmodestino** [comment]
ah went back to fluentd v12.40 and am back up. :

 ```&& echo 'gem: --no-document' >> /etc/gemrc \
 && gem install oj -v 2.18.3 \
 && gem install json -v 2.1.0 \
 && gem install fluentd -v 0.12.40 \
 && gem install fluent-plugin-record-reformer \
 && gem install fluent-plugin-splunkhec \
 && gem install fluent-plugin-kubernetes_metadata_filter \
 && gem install ffi \
 && gem install fluent-plugin-systemd -v 0.0.8 \
```
It must have been something with fluentd -v v0.14.22.rc1, which I tried to flipped to

**Comment by repeatedly** [comment]
This was old issue. Closed.
