### ISSUE TITLE
cannot load gelf plugin

### ISSUE THREAD

**Issue by profhase** [fluent/fluentd-docker-image#145]
I am using the `fluent/fluentd:v1.2` image

I mount it with `-v /etc/fluentd/plugins:/fluentd/plugins` and copy this file into the mounted volume

`https://github.com/bodhi-space/fluent-plugin-gelf-hs/blob/master/lib/fluent/plugin/out_gelf.rb`

Upon container start I am getting the message
`cannot load such file --gelf`

```
cannot load such file -- gelf (LoadError)
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /etc/fluent/plugin/out_gelf.rb:15:in `initialize'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/plugin.rb:149:in `new'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/plugin.rb:149:in `new_impl'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/plugin.rb:104:in `new_output'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/agent.rb:128:in `add_match'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/agent.rb:72:in `block in configure'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/agent.rb:64:in `each'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/agent.rb:64:in `configure'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/root_agent.rb:112:in `configure'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/engine.rb:131:in `configure'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/engine.rb:96:in `run_configure'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/supervisor.rb:795:in `run_configure'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/supervisor.rb:579:in `dry_run'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/supervisor.rb:597:in `supervise'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/supervisor.rb:502:in `run_supervisor'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/lib/ruby/gems/2.4.0/gems/fluentd-1.2.6/bin/fluentd:8:in `<top (required)>'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/bin/fluentd:23:in `load'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_1  |         from /usr/bin/fluentd:23:in `<main>'
Oct 30 11:28:40 master-test-bi-01 docker-compose[45672]: fluentd_fluentd_1 exited with code 1

```

What am I doing wrong?
Thanks a lot

**Comment by repeatedly** [comment]
> What am I doing wrong?

Need to install gelf library because out_gelf depends on it.

**Comment by profhase** [comment]
@repeatedly : Can I just drop it somehow into the plugins folder or do I have to build my own image based on fluentd?

**Comment by repeatedly** [comment]
> Can I just drop it somehow into the plugins folder or do I have to build my own image based on fluentd?

Latter is better because gelf library has lots of files. Install gelf via rubygems is safer.

**Comment by kenhys** [comment]
https://github.com/fluent/fluentd-docker-image/issues/145#issuecomment-434628195
https://github.com/fluent/fluentd-docker-image/issues/145#issuecomment-439243761　

These answers will solve this issue.
