### ISSUE TITLE
New images, v1.3.2-1.0/v1.3.2-debian-1.0 are crashing

### ISSUE THREAD

**Issue by varun-da** [fluent/fluentd-docker-image#165]
Images with new tag scheme are crashing, `v1.3.2-1.0`/`v1.3.2-debian-1.0` with the following error:

```
2018-12-26 22:22:12 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2018-12-26 22:22:12 +0000 [error]: config error file="/fluentd/etc/fluent.conf" error_class=Fluent::ConfigError error="out_file: `/fluentd/log//.log` is not writable"
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin/out_file.rb:148:in `configure'
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/plugin.rb:164:in `configure'
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/agent.rb:130:in `add_match'
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/agent.rb:72:in `block in configure'
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/agent.rb:64:in `each'
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/agent.rb:64:in `configure'
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/root_agent.rb:112:in `configure'
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/engine.rb:131:in `configure'
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/engine.rb:96:in `run_configure'
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/supervisor.rb:795:in `run_configure'
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/supervisor.rb:579:in `dry_run'
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/supervisor.rb:597:in `supervise'
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/supervisor.rb:502:in `run_supervisor'
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
  2018-12-26 22:22:12 +0000 [debug]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-12-26 22:22:12 +0000 [debug]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2018-12-26 22:22:12 +0000 [debug]: /var/lib/gems/2.3.0/gems/fluentd-1.3.2/bin/fluentd:8:in `<top (required)>'
  2018-12-26 22:22:12 +0000 [debug]: /usr/local/bin/fluentd:22:in `load'
  2018-12-26 22:22:12 +0000 [debug]: /usr/local/bin/fluentd:22:in `<main>'
```

Using images `v1.3.2`/`v1.3.2-debian` work fine with the same config.

**Comment by ohadlahav** [comment]
Same here

**Comment by repeatedly** [comment]
> /fluentd/log//.log

It seems path of `out_file` is broken. What configuration file do you use?

**Comment by kenhys** [comment]
I'll close non-supported old image issue.
