### ISSUE TITLE
cannot load such file -- fluent/plugin/out_splunk

### ISSUE THREAD

**Issue by totee19** [fluent/fluentd-docker-image#237]
Hello,

I try to build my own docker image from fluentd image. 
I  added plugins : 
- fluent-plugin-splunk-hec
- fluent-plugin-secure-forward

But when launch my image I have this message:

```
docker run -p 24224:24224 -ti --rm -v /root/fluentd/etc:/fluentd/etc --name fluentd custom-fluentd:v0.1

2020-10-31 19:27:15 +0000 [info]: parsing config file is succeeded path="/fluentd/etc/fluent.conf"
2020-10-31 19:27:15 +0000 [info]: gem 'fluent-plugin-secure-forward' version '0.4.5'
2020-10-31 19:27:15 +0000 [info]: gem 'fluent-plugin-splunk-hec' version '1.2.4'
2020-10-31 19:27:15 +0000 [info]: gem 'fluentd' version '1.11.4'
2020-10-31 19:27:15 +0000 [info]: starting fluentd-1.11.4 as dry run mode ruby="2.6.6"
Traceback (most recent call last):
	24: from /usr/local/bundle/bin/fluentd:23:in `<main>'
	23: from /usr/local/bundle/bin/fluentd:23:in `load'
	22: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/bin/fluentd:8:in `<top (required)>'
	21: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	20: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	19: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/command/fluentd.rb:341:in `<top (required)>'
	18: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/supervisor.rb:556:in `run_supervisor'
	17: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/engine.rb:80:in `run_configure'
	16: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/engine.rb:105:in `configure'
	15: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/root_agent.rb:146:in `configure'
	14: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/agent.rb:64:in `configure'
	13: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/agent.rb:64:in `each'
	12: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/agent.rb:74:in `block in configure'
	11: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/agent.rb:130:in `add_match'
	10: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/plugin.rb:109:in `new_output'
	 9: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/plugin.rb:155:in `new_impl'
	 8: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/registry.rb:44:in `lookup'
	 7: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/registry.rb:99:in `search'
	 6: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/registry.rb:99:in `each'
	 5: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/registry.rb:102:in `block in search'
	 4: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 3: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	 2: from /usr/local/lib/ruby/gems/2.6.0/gems/fluent-plugin-splunk-hec-1.2.4/lib/fluent/plugin/out_splunk_hec.rb:7:in `<top (required)>'
	 1: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- fluent/plugin/out_splunk (LoadError)
	39: from /usr/local/bundle/bin/fluentd:23:in `<main>'
	38: from /usr/local/bundle/bin/fluentd:23:in `load'
	37: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/bin/fluentd:8:in `<top (required)>'
	36: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	35: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	34: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/command/fluentd.rb:341:in `<top (required)>'
	33: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/supervisor.rb:556:in `run_supervisor'
	32: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/engine.rb:80:in `run_configure'
	31: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/engine.rb:105:in `configure'
	30: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/root_agent.rb:146:in `configure'
	29: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/agent.rb:64:in `configure'
	28: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/agent.rb:64:in `each'
	27: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/agent.rb:74:in `block in configure'
	26: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/agent.rb:130:in `add_match'
	25: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/plugin.rb:109:in `new_output'
	24: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/plugin.rb:155:in `new_impl'
	23: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/registry.rb:44:in `lookup'
	22: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/registry.rb:99:in `search'
	21: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/registry.rb:99:in `each'
	20: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/registry.rb:102:in `block in search'
	19: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	18: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	17: from /usr/local/lib/ruby/gems/2.6.0/gems/fluent-plugin-splunk-hec-1.2.4/lib/fluent/plugin/out_splunk_hec.rb:7:in `<top (required)>'
	16: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	15: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
	14: from /usr/local/lib/ruby/2.6.0/rubygems.rb:217:in `try_activate'
	13: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	12: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	11: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	10: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	 9: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	 8: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	 7: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 6: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	 5: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	 4: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	 3: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 2: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	 1: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1418:in `activate'
/usr/local/lib/ruby/2.6.0/rubygems/specification.rb:2302:in `raise_if_conflicts': Unable to activate activesupport-6.0.3.4, because tzinfo-2.0.2 conflicts with tzinfo (~> 1.1) (Gem::ConflictError)
	40: from /usr/local/bundle/bin/fluentd:23:in `<main>'
	39: from /usr/local/bundle/bin/fluentd:23:in `load'
	38: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/bin/fluentd:8:in `<top (required)>'
	37: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	36: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	35: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/command/fluentd.rb:341:in `<top (required)>'
	34: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/supervisor.rb:556:in `run_supervisor'
	33: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/engine.rb:80:in `run_configure'
	32: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/engine.rb:105:in `configure'
	31: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/root_agent.rb:146:in `configure'
	30: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/agent.rb:64:in `configure'
	29: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/agent.rb:64:in `each'
	28: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/agent.rb:74:in `block in configure'
	27: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/agent.rb:130:in `add_match'
	26: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/plugin.rb:109:in `new_output'
	25: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/plugin.rb:155:in `new_impl'
	24: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/registry.rb:44:in `lookup'
	23: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/registry.rb:99:in `search'
	22: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/registry.rb:99:in `each'
	21: from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.11.4/lib/fluent/registry.rb:102:in `block in search'
	20: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	19: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	18: from /usr/local/lib/ruby/gems/2.6.0/gems/fluent-plugin-splunk-hec-1.2.4/lib/fluent/plugin/out_splunk_hec.rb:7:in `<top (required)>'
	17: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:34:in `require'
	16: from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
	15: from /usr/local/lib/ruby/2.6.0/rubygems.rb:216:in `try_activate'
	14: from /usr/local/lib/ruby/2.6.0/rubygems.rb:223:in `rescue in try_activate'
	13: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	12: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	11: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	10: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	 9: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	 8: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	 7: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 6: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	 5: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	 4: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	 3: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	 2: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1452:in `block in activate_dependencies'
	 1: from /usr/local/lib/ruby/2.6.0/rubygems/specification.rb:1418:in `activate'
/usr/local/lib/ruby/2.6.0/rubygems/specification.rb:2302:in `raise_if_conflicts': Unable to activate activesupport-6.0.3.4, because tzinfo-2.0.2 conflicts with tzinfo (~> 1.1) (Gem::ConflictError) 

```

Here is my Docker file :

```
FROM fluent/fluentd:v1.11-debian-1

ENV HTTP_PROXY=http://x.x.x.x:8080

# Use root account to use apt
USER root


RUN buildDeps="sudo make gcc g++ libc-dev ruby-dev" \
#RUN buildDeps="sudo gem" \
 && apt-get update \
 && apt-get install -y --no-install-recommends $buildDeps \
 && sudo gem install  --http-proxy=${HTTP_PROXY} fluent-plugin-splunk-hec \
 && sudo gem install  --http-proxy=${HTTP_PROXY} fluent-plugin-secure-forward\
 && sudo gem sources --clear-all \
 && SUDO_FORCE_REMOVE=yes \
    apt-get purge -y --auto-remove \
                  -o APT::AutoRemove::RecommendsImportant=false \
                  $buildDeps \
 && rm -rf /var/lib/apt/lists/* \
 && rm -rf /tmp/* /var/tmp/* /usr/lib/ruby/gems/*/cache/*.gem

COPY fluent.conf /fluentd/etc/
COPY entrypoint.sh /bin/

USER fluent
```

Tree directory of my configuration

```

/root/fluentd/
└── etc
    ├── certs
    │   ├── ca_cert.pem
    │   └── ca_key.pem
    ├── fluent.conf
    └── plugin
        ├── secure-forward.conf
        └── splunk-hec.conf

fluentd.conf
@include /fluentd/etc/plugin/*.conf

```

**Comment by zeldigas** [comment]
Faced with same problem. `gem list` shows 2 versions installed `tzinfo (2.0.2, 1.2.7)`. 
I bet it's not proper way to fix issue, but at least manual remova of 2.0.2 fixes startup, just add `gem uninstall tzinfo -v 2.0.2` after installing plugins

**Comment by totee19** [comment]
It's working.
Thank you

**Comment by repeatedly** [comment]
Thanks. Just added this point to FAQ: https://docs.fluentd.org/quickstart/faq#fluentd-raises-tzinfo-conflict-error-after-installed-plugins
