### ISSUE TITLE
Dockefile to install plugins from README.md failing - entrypoint.sh not found

### ISSUE THREAD

**Issue by siddharth** [fluent/fluentd-docker-image#257]
Hi,

Have tried both the Dockerfile examples (1.12-1 debian and alpine) as per current README.md  for installing elasticsearch plugin but I keep getting the following error :

```
Building fluentd
[+] Building 5.7s (9/9) FINISHED                                                                                                                      
 => [internal] load build definition from Dockerfile                                                                                             0.5s
 => => transferring dockerfile: 760B                                                                                                             0.0s
 => [internal] load .dockerignore                                                                                                                0.6s
 => => transferring context: 2B                                                                                                                  0.0s
 => [internal] load metadata for docker.io/fluent/fluentd:v1.12-1                                                                                4.1s
 => [auth] fluent/fluentd:pull token for registry-1.docker.io                                                                                    0.0s
 => [internal] load build context                                                                                                                0.4s
 => => transferring context: 2B                                                                                                                  0.0s
 => CANCELED [1/4] FROM docker.io/fluent/fluentd:v1.12-1@sha256:d0e250375b6383b287cc22c03382851af09b5f0d75ba533da247f3b772becb6c                 0.6s
 => => resolve docker.io/fluent/fluentd:v1.12-1@sha256:d0e250375b6383b287cc22c03382851af09b5f0d75ba533da247f3b772becb6c                          0.2s
 => => sha256:d0e250375b6383b287cc22c03382851af09b5f0d75ba533da247f3b772becb6c 1.36kB / 1.36kB                                                   0.0s
 => => sha256:76c4f38180a4e1b1c59a94da949c24b4e62de07381cbdf5c666e2218857ebef6 4.83kB / 4.83kB                                                   0.0s
 => CACHED [2/4] RUN apk add --no-cache --update --virtual .build-deps         sudo build-base ruby-dev  && sudo gem install fluent-plugin-elas  0.0s
 => ERROR [3/4] COPY fluent.conf /fluentd/etc/                                                                                                   0.0s
 => ERROR [4/4] COPY entrypoint.sh /bin/                                                                                                         0.0s
------
 > [3/4] COPY fluent.conf /fluentd/etc/:
------
------
 > [4/4] COPY entrypoint.sh /bin/:
------
failed to compute cache key: "/entrypoint.sh" not found: not found
ERROR: Service 'fluentd' failed to build

```

Please help!

**Comment by cosmo0920** [comment]
Did you follow `1. Create a working directory` step?
https://github.com/fluent/fluentd-docker-image#1-create-a-working-directory

**Comment by siddharth** [comment]
Hi @cosmo0920 ,
Thanks, I had just skipped to the dockerfile, my bad!
However even after that, the container builds now but upon running via docker-compose up, it shows a state of "Exit 1" in docker-compose ps output. I checked the logs and this is what shows up :

```
/usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.12.1/lib/fluent/config.rb:31:in `initialize': No such file or directory @ rb_sysopen - /fluentd/etc/fluent.conf (Errno::ENOENT)
 	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.12.1/lib/fluent/config.rb:31:in `open'
 	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.12.1/lib/fluent/config.rb:31:in `build'
 	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.12.1/lib/fluent/supervisor.rb:727:in `configure'
 	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.12.1/lib/fluent/command/fluentd.rb:344:in `<top (required)>'
 	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
 	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
 	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.12.1/bin/fluentd:8:in `<top (required)>'
 	from /usr/local/bundle/bin/fluentd:23:in `load'
 	from /usr/local/bundle/bin/fluentd:23:in `<main>'
 /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.12.1/lib/fluent/config.rb:31:in `initialize': No such file or directory @ rb_sysopen - /fluentd/etc/fluent.conf (Errno::ENOENT)
 	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.12.1/lib/fluent/config.rb:31:in `open'
 	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.12.1/lib/fluent/config.rb:31:in `build'
 	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.12.1/lib/fluent/supervisor.rb:727:in `configure'
 	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.12.1/lib/fluent/command/fluentd.rb:344:in `<top (required)>'
 	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
 	from /usr/local/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
 	from /usr/local/lib/ruby/gems/2.6.0/gems/fluentd-1.12.1/bin/fluentd:8:in `<top (required)>'
 	from /usr/local/bundle/bin/fluentd:23:in `load'
 	from /usr/local/bundle/bin/fluentd:23:in `<main>'
```

**Comment by kenhys** [comment]
Maybe you didn't build the image itself correctly.
Read https://github.com/fluent/fluentd-docker-image/blob/master/README.md#1-create-a-working-directory
section carefully and follow it.

**Comment by siddharth** [comment]
Ok, went ahead and rechecked everything. There was no problem with this setup and it was exactly as per the spec, however I had a docker-compose entry from earlier which was causing this conflict - 

`    volumes:
    - ./docker-compose/fluentd/conf:/fluentd/etc
`
Building fine once I removed these. Thanks for the help!
