### ISSUE TITLE
Failed Mounting Multiple Volume

### ISSUE THREAD

**Issue by Spycomb** [fluent/fluentd-docker-image#40]
Host Os: Windows
Docker Command :
docker run -p 24224:24224 -e FLUENTD_CONF=fluent.conf -v //c//Users//user//fluentd//logs://fluentd//log -v //c//Users//user//fluentd//config://fluentd//etc fluent/fluentd

Logs : 

    #.... blah blah blah and then fluentd config   
      <source>
    type forward
    port 24224
    bind 0.0.0.0
	  </source>
	  <match *.*>
	    type stdout
	  </match>
	</ROOT>
	2016-07-01 08:38:43 +0000 [info]: listening fluent socket on 0.0.0.0:24224
	2016-07-01 08:38:43 +0000 [info]: listening fluent socket on 0.0.0.0:24224
	2016-07-01 08:38:43 +0000 [error]: unexpected error error_class=Errno::EADDRINUSE error=#<Errno::EADDRINUSE: Address in use - bind(2) for "0.0.0.0" port 24224>
	  2016-07-01 08:38:43 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.4/lib/cool.io/server.rb:57:in `initialize'
	  2016-07-01 08:38:43 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/cool.io-1.4.4/lib/cool.io/server.rb:57:in `new'

if i only mount 1 volume it works well
can anyone help me to find out why fluentd tries to listen to the socket twice when i tries to mount 2 volume?

**Comment by Spycomb** [comment]
sorry the problem is on my fluentd config :|
