### ISSUE TITLE
fluent-plugin-systemd depends on libsystemd 

### ISSUE THREAD

**Issue by jescarri** [fluent/fluentd-docker-image#49]
I can't find a binary distribution of libsystemd on the apk repositories, what's the best way to use the fluentd docker image and fluent-plugin-systemd ?

**Comment by repeatedly** [comment]
AFAIK, Alpine Linux doesn't use systemd and they don't focus on systemd support.
I'm not sure how to use systemd in Alpine Linux.
if you need to use systemd in your container, using ubuntu or other OS is better.

**Comment by jescarri** [comment]
Yea, I went into that route, using debian, maybe deprecating the Ubuntu image is not a good idea?

**Comment by tyranron** [comment]
Having the same issue and agree with @jescarri.
It would be nice to have Debian/Ubuntu based official images of fluentd for building own images on top of them.
Why not support both Alpine and Ubuntu/Debian version as official images usually do ([Nginx](https://hub.docker.com/r/library/nginx/tags/), [PHP](https://hub.docker.com/r/library/php/tags/))?

**Comment by jescarri** [comment]
I have something already, I will submit a PR, in the afternoon.

**Comment by tyranron** [comment]
@jescarri any news?

**Comment by kuroneko25** [comment]
We have the same issue here. Any updates? Meanwhile what is a good workaround?

**Comment by repeatedly** [comment]
ubuntu-base tag doesn't work?

**Comment by kuroneko25** [comment]
fluent-plugin-systemd is running into issues with not finding the libsystemd dependency. I've forked the ubuntu image and added `app-get-install libsystemd-journal0`.

```
2016-11-15T22:33:44.025186588Z 2016-11-15 22:33:44 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
2016-11-15T22:33:44.027556160Z 2016-11-15 22:33:44 +0000 [info]: starting fluentd-0.12.26
2016-11-15T22:33:44.089074703Z 2016-11-15 22:33:44 +0000 [info]: gem 'fluent-plugin-kubernetes_metadata_filter' version '0.26.2'
2016-11-15T22:33:44.089100686Z 2016-11-15 22:33:44 +0000 [info]: gem 'fluent-plugin-systemd' version '0.0.5'
2016-11-15T22:33:44.089168695Z 2016-11-15 22:33:44 +0000 [info]: gem 'fluentd' version '0.12.26'
2016-11-15T22:33:44.089243919Z 2016-11-15 22:33:44 +0000 [info]: adding match pattern="fluent.**" type="null"
2016-11-15T22:33:44.089455429Z 2016-11-15 22:33:44 +0000 [info]: adding filter pattern="kubernetes.**" type="kubernetes_metadata"
2016-11-15T22:33:44.378391986Z 2016-11-15 22:33:44 +0000 [info]: adding match pattern="kubernetes.**" type="splunk_ex"
2016-11-15T22:33:44.378645013Z 2016-11-15 22:33:44 +0000 [info]: adding source type="tail"
2016-11-15T22:33:44.381014587Z 2016-11-15 22:33:44 +0000 [info]: adding source type="systemd"
2016-11-15T22:33:44.402172285Z /home/ubuntu/.gem/ruby/2.2.0/gems/ffi-1.9.14/lib/ffi/library.rb:147:in `block in ffi_lib': Could not open library 'libsystemd.so.0': libsystemd.so.0: cannot open shared object file: No such file or directory. (LoadError)
2016-11-15T22:33:44.402222852Z Could not open library 'libsystemd.so': libsystemd.so: cannot open shared object file: No such file or directory.
2016-11-15T22:33:44.402227685Z Could not open library 'libsystemd-id128.so.0': libsystemd-id128.so.0: cannot open shared object file: No such file or directory.
2016-11-15T22:33:44.402230810Z Could not open library 'libsystemd-id128.so': libsystemd-id128.so: cannot open shared object file: No such file or directory
2016-11-15T22:33:44.402234056Z 	from /home/ubuntu/.gem/ruby/2.2.0/gems/ffi-1.9.14/lib/ffi/library.rb:100:in `map'
2016-11-15T22:33:44.402240983Z 	from /home/ubuntu/.gem/ruby/2.2.0/gems/ffi-1.9.14/lib/ffi/library.rb:100:in `ffi_lib'
2016-11-15T22:33:44.402244355Z 	from /home/ubuntu/.gem/ruby/2.2.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:48:in `<module:Native>'
2016-11-15T22:33:44.402247336Z 	from /home/ubuntu/.gem/ruby/2.2.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:45:in `<module:Id128>'
2016-11-15T22:33:44.402250630Z 	from /home/ubuntu/.gem/ruby/2.2.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:6:in `<module:Systemd>'
2016-11-15T22:33:44.402253658Z 	from /home/ubuntu/.gem/ruby/2.2.0/gems/systemd-journal-1.2.3/lib/systemd/id128.rb:3:in `<top (required)>'
```

**Comment by Lawouach** [comment]
Just a comment on not supporting Ubuntu images when some native plugins may not be compile with Alpine. This is unfortunate.

**Comment by tyranron** [comment]
+1 to @Lawouach  

@repeatedly repeating my question: is there any real reason not to support both Ubuntu/Debian-based and Alpine-based images?  
If not, I can contribute stuff.

**Comment by repeatedly** [comment]
I don't have a enough time to maintain two versions.
If someone can continue to improve ubuntu based image, fix bug / handle issue and questions an etc,
I can accept it.

**Comment by tyranron** [comment]
@repeatedly I can help and improve project layout/stuff to make image maintaining easier.

I'll submit PR in a week or so, if you don't mind.

**Comment by repeatedly** [comment]
Okay. I will wait it ;)

**Comment by schasse** [comment]
same issue here

**Comment by repeatedly** [comment]
https://github.com/fluent/fluentd-docker-image/pull/71 is patch for this issue.
From our experience, almost td-agent users are CentOS(RHEL) or Ubuntu.
So I want to know debian is ok or not.

**Comment by tyranron** [comment]
Ok, let's see...

Container is not a VM, it's rather a single running application. So the distros difference is not a concern here. What we really need here is:
1. GNU libc based distro.
2. Convenient package tool to install system dependencies for Fluentd plugins.

All the distros - CentOS, Ubuntu and Debian - meet these requirements quite well.

The reasons why choose Debian are:
- Debian images have `slim` versions which are the lightest ones (~30 MB Debian vs ~40 MB Ubuntu vs ~70 MB CentOS)
- Most popular official images have their main version based on Debian: [PHP](https://github.com/docker-library/php/blob/9abc1efe542b56aa93835e4987d5d4a88171b232/7.1/Dockerfile), [Nginx](https://github.com/nginxinc/docker-nginx/blob/e950fa7dfcee74933b1248a7fe345bdbc176fffb/mainline/jessie/Dockerfile), [Apache](https://github.com/docker-library/httpd/blob/e885c0d63078153dc89fa0212314e590fec7fc93/2.4/Dockerfile), [Memcached](https://github.com/docker-library/memcached/blob/53b91f1cfb308fe4946a79bd1d23ceaa3d18e250/debian/Dockerfile), [MySQL](https://github.com/docker-library/mysql/blob/eeb0c33dfcad3db46a0dfb24c352d2a1601c7667/5.7/Dockerfile), [Postgres](https://github.com/docker-library/postgres/blob/d7accc9c8c7d740ad756b887225fe31286d98f64/9.6/Dockerfile), even [Ruby](https://github.com/docker-library/ruby/blob/bae23407cd2c07756c8f88095a25129bf204efaf/2.4/Dockerfile), and so on...

**Comment by repeatedly** [comment]
Yes but package versions and maintenance policy is different.
I don't have a counter opinion for Debian.
So if users are ok for debian, I can merge the patch.

**Comment by repeatedly** [comment]
If there is no objection for debian, I will merge #71 tomorrow.

**Comment by tyranron** [comment]
@schasse @Lawouach @kuroneko25 @jescarri  
The repo contains supported Debian based image now.

**Comment by repeatedly** [comment]
This issue should be fixed by Debian based image.
