### ISSUE TITLE
docker images v0.14.2 & v0.14.6 are broken

### ISSUE THREAD

**Issue by moleksyuk** [fluent/fluentd-docker-image#52]
Hi,

I have issue with running docker images with version `v0.14.2` & `v0.14.6` but everything works fine with `v0.14.1`.

**v0.14.2**
```
docker run -p 24224:2224 fluent/fluentd:v0.14.2
```

but getting this error:
```
2016-09-14 14:46:32 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
2016-09-14 14:46:32 +0000 [info]: starting fluentd-0.14.2
2016-09-14 14:46:32 +0000 [info]: spawn command to main: /usr/bin/ruby -Eascii-8bit:ascii-8bit /usr/bin/fluentd -c /fluentd/etc/fluent.conf -p /fluentd/plugins --under-supervisor
2016-09-14 14:46:32 +0000 [info]: reading config file path="/fluentd/etc/fluent.conf"
2016-09-14 14:46:32 +0000 [info]: starting fluentd-0.14.2 without supervision
2016-09-14 14:46:32 +0000 [info]: gem 'fluentd' version '0.14.2'
2016-09-14 14:46:32 +0000 [info]: adding match in @mainstream pattern="docker.**" type="file"
2016-09-14 14:46:32 +0000 [info]: adding match in @mainstream pattern="**" type="file"
2016-09-14 14:46:32 +0000 [info]: adding filter pattern="**" type="stdout"
2016-09-14 14:46:32 +0000 [info]: adding source type="forward"
2016-09-14 14:46:32 +0000 [info]: using configuration file: <ROOT>
  <source>
    @type forward
    @id input1
    @label @mainstream
    port 24224
  </source>
  <filter **>
    @type stdout
  </filter>
  <label @mainstream>
    <match docker.**>
      @type file
      @id output_docker1
      path "/fluentd/log/docker.*.log"
      symlink_path "/fluentd/log/docker.log"
      append true
      time_slice_format "%Y%m%d"
      time_slice_wait 1m
      time_format "%Y%m%dT%H%M%S%z"
      buffer_path /fluentd/log/docker.*.log
      <buffer time>
        flush_mode lazy
        retry_type exponential_backoff
        path /fluentd/log/docker.*.log
        timekey_wait 1m
        timekey 86400
      </buffer>
      <parse>
        time_format %Y%m%dT%H%M%S%z
      </parse>
      <inject>
        time_format %Y%m%dT%H%M%S%z
      </inject>
    </match>
    <match **>
      @type file
      @id output1
      path "/fluentd/log/data.*.log"
      symlink_path "/fluentd/log/data.log"
      append true
      time_slice_format "%Y%m%d"
      time_slice_wait 10m
      time_format "%Y%m%dT%H%M%S%z"
      buffer_path /fluentd/log/data.*.log
      <buffer time>
        flush_mode lazy
        retry_type exponential_backoff
        path /fluentd/log/data.*.log
        timekey_wait 10m
        timekey 86400
      </buffer>
      <parse>
        time_format %Y%m%dT%H%M%S%z
      </parse>
      <inject>
        time_format %Y%m%dT%H%M%S%z
      </inject>
    </match>
  </label>
</ROOT>
2016-09-14 14:46:32 +0000 [warn]: section <parse> is not used in <match docker.**> of out_file plugin
2016-09-14 14:46:32 +0000 [warn]: section <parse> is not used in <match **> of out_file plugin
2016-09-14 14:46:32 +0000 [error]: unexpected error error_class=NameError error="uninitialized constant Fluent::Compat::HandleTagAndTimeMixin\nDid you mean?  Fluent::Compat::HandleTagNameMixin\n               Fluent::HandleTagNameMixin"
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/compat/output.rb:655:in `start'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/compat/call_super_mixin.rb:42:in `start'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/root_agent.rb:138:in `block in start'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/root_agent.rb:117:in `block (2 levels) in lifecycle'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/agent.rb:125:in `block (2 levels) in lifecycle'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/agent.rb:124:in `each'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/agent.rb:124:in `block in lifecycle'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/agent.rb:117:in `each'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/agent.rb:117:in `lifecycle'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/root_agent.rb:116:in `block in lifecycle'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/root_agent.rb:113:in `each'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/root_agent.rb:113:in `lifecycle'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/root_agent.rb:137:in `start'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/engine.rb:211:in `start'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/engine.rb:175:in `run'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/supervisor.rb:624:in `run_engine'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/supervisor.rb:409:in `block in run_worker'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/supervisor.rb:553:in `main_process'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/supervisor.rb:404:in `run_worker'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/lib/fluent/command/fluentd.rb:271:in `<top (required)>'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  2016-09-14 14:46:32 +0000 [error]: /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.2/bin/fluentd:5:in `<top (required)>'
  2016-09-14 14:46:32 +0000 [error]: /usr/bin/fluentd:23:in `load'
  2016-09-14 14:46:32 +0000 [error]: /usr/bin/fluentd:23:in `<main>'
2016-09-14 14:46:32 +0000 [error]: unexpected error error="uninitialized constant Fluent::Compat::HandleTagAndTimeMixin\nDid you mean?  Fluent::Compat::HandleTagNameMixin\n               Fluent::HandleTagNameMixin"
  2016-09-14 14:46:32 +0000 [error]: suppressed same stacktrace
2016-09-14 14:46:33 +0000 [info]: Worker 0 finished unexpectedly with status 1
```

---
**v0.14.6**
```
docker run -p 24224:2224 fluent/fluentd:v0.14.6
```

but getting this error:

```
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
       	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/config/literal_parser.rb:19:in `<top (required)>'
       	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/config/element.rb:18:in `<top (required)>'
       	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/config.rb:18:in `<top (required)>'
       	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/supervisor.rb:20:in `<top (required)>'
       	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/lib/fluent/command/fluentd.rb:19:in `<top (required)>'
       	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
       	from /usr/lib/ruby/gems/2.3.0/gems/fluentd-0.14.6/bin/fluentd:5:in `<top (required)>'
       	from /usr/bin/fluentd:23:in `load'
       	from /usr/bin/fluentd:23:in `<main>'
```

**Comment by moleksyuk** [comment]
Issue was related to not installed json package:

```
gem install --no-document json_pure jemalloc
```
