### ISSUE TITLE
fluent volume pos_file gets permission denied

### ISSUE THREAD

**Issue by aeoluswing** [fluent/fluentd-docker-image#90]
After using docker image fluent:v0.12-debian-onbuild to deploy the fluent daemonsets via kubernetes,I got something wrong with user mapping.I have checked out my container logs:
```useradd: failed to reset the faillog entry of UID 1000: Read-only file system
useradd: failed to reset the lastlog entry of UID 1000: Read-only file system
2017-07-26 08:54:37 +0800 [info]: reading config file path="/fluentd/etc/fluent.conf"
2017-07-26 08:54:37 +0800 [info]: starting fluentd-0.12.37
2017-07-26 08:54:37 +0800 [info]: gem 'fluent-plugin-elasticsearch' version '1.9.5'
2017-07-26 08:54:37 +0800 [info]: gem 'fluentd' version '0.12.37'
2017-07-26 08:54:37 +0800 [info]: adding match pattern="*.*" type="copy"
2017-07-26 08:54:37 +0800 [info]: adding source type="tail"
2017-07-26 08:54:37 +0800 [info]: adding source type="tail"
2017-07-26 08:54:37 +0800 [info]: adding source type="tail"
2017-07-26 08:54:37 +0800 [info]: adding source type="tail"
2017-07-26 08:54:37 +0800 [info]: using configuration file: 
<ROOT>
  <source>
    @type tail
    path /var/lib/docker/containers/*/*-json.log
    tag container.docker
    time_format %Y-%m-%dT%H:%M:%S.%N
    format /^(?<all>.*)$/
    pos_file /var/tmp/pos-file/container-docker.log.pos
  </source>
  <match *.*>
    type copy
    <store>
      type elasticsearch
      host efk-elasticsearch.kube-system
      port 9200
      include_tag_key true
      index_name container
      type_name container
      logstash_format true
      logstash_prefix container
      flush_interval 5s
    </store>
  </match>
</ROOT>
2017-07-26 08:54:37 +0800 [error]: unexpected error error_class=Errno::EACCES error=#<Errno::EACCES: Permission denied @ rb_sysopen - /var/tmp/pos-file/container-docker.log.pos>
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/plugin/in_tail.rb:132:in `initialize'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/plugin/in_tail.rb:132:in `open'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/plugin/in_tail.rb:132:in `start'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/root_agent.rb:115:in `block in start'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/root_agent.rb:114:in `each'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/root_agent.rb:114:in `start'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/engine.rb:237:in `start'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/engine.rb:187:in `run'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/supervisor.rb:570:in `run_engine'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/supervisor.rb:162:in `block in start'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/supervisor.rb:366:in `main_process'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/supervisor.rb:339:in `block in supervise'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/supervisor.rb:338:in `fork'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/supervisor.rb:338:in `supervise'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/supervisor.rb:156:in `start'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/lib/fluent/command/fluentd.rb:173:in `<top (required)>'
2017-07-26 08:54:37 +0800 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2017-07-26 08:54:37 +0800 [error]: /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
2017-07-26 08:54:37 +0800 [error]: /var/lib/gems/2.3.0/gems/fluentd-0.12.37/bin/fluentd:5:in `<top (required)>'
2017-07-26 08:54:37 +0800 [error]: /usr/local/bin/fluentd:22:in `load'
2017-07-26 08:54:37 +0800 [error]: /usr/local/bin/fluentd:22:in `<main>'
2017-07-26 08:54:37 +0800 [info]: shutting down fluentd
2017-07-26 08:54:37 +0800 [info]: shutting down output type="copy" plugin_id="object:3ff7af1492f4"
2017-07-26 08:54:37 +0800 [info]: process finished code=0
2017-07-26 08:54:37 +0800 [warn]: process died within 1 second. exit.
```

this image starts fluent by user fluent,which mapping uid 1000 but makes 'useradd error'.I change the volume directory ownership by command 'chown -R 1000:1000 /var/tmp/pos-file' and it works.But how does this happen and what's more,could anyone have ideas how to fix this issue via Dockerfile?

**Comment by repeatedly** [comment]
I'm not sure which is the problem but if you want to use fluentd on kubernetes daemonset, consider https://github.com/fluent/fluentd-kubernetes-daemonset first.

**Comment by aeoluswing** [comment]
Further more,I search [use root in fluent image](https://github.com/fluent/fluentd-docker-image/issues/48),and follow the step 'USER root' in my Dockerfile,but it still gets the same error:
```
useradd: failed to reset the faillog entry of UID 1000: Read-only file system
useradd: failed to reset the lastlog entry of UID 1000: Read-only file system
```
and Dockerfile:
```
FROM fluent/fluentd:v0.12-debian-onbuild

USER root
RUN mkdir -p /var/tmp/pos-file

CMD ["/bin/sh","-c","fluentd -c /fluentd/etc/${FLUENTD_CONF} -p /fluentd/plugins $FLUENTD_OPT"]
```
In my opinion,RO file system can not write pos-file which leading  to 'Permission denied'.Could anyone fix this issue?

**Comment by aeoluswing** [comment]
@repeatedly,the image(fluent/fluentd-kubernetes-daemonset:elasticsearch) works,and tail container log files(both /var/lib/docker/containers/*.log and /other/path/to/persistentlog) successfully,I find 'root' is the user who launch fluent in this image:
```
/home/fluent # ps
PID   USER     TIME   COMMAND
    1 root       0:00 {fluentd} /usr/bin/ruby /usr/bin/fluentd -c /fluentd/etc/
    8 root       0:01 {fluentd} /usr/bin/ruby /usr/bin/fluentd -c /fluentd/etc/
``` 
and volume pos-file on host is writable:
```
-rw-r--r-- 1 root root  241 Jul 26 10:03 container-debug.log.pos
-rw-r--r-- 1 root root 8000 Jul 26 10:06 container-docker.log.pos
-rw-r--r-- 1 root root  241 Jul 26 10:03 container-error.log.pos
-rw-r--r-- 1 root root  238 Jul 26 10:03 container-info.log.pos
```
Thus it can be seen,this issue is related to user mapping and fluent daemonset image has fixed this issue.I'll close this.
Thanks a lot!!

**Comment by bboreham** [comment]
I'm getting this issue too, when trying to upgrade from 14.2 to 14.20.  Seems to me that #78 is what changed.

I cannot see anything in fluentd-kubernetes-daemonset which would fix this - can you help point to it?
(I want to have different config, e.g. buffered upload, so don't want to just install that daemonset directly)

**Comment by bboreham** [comment]
Oh, I see - there's a different `Dockerfile` in fluentd-kubernetes-daemonset which doesn't do the change-user thing at all.

**Comment by reymont** [comment]
This is my workround. Maybe contains potential permission issues.

1. Modify the [entrypoint.sh](https://github.com/fluent/fluentd-docker-image/blob/master/v0.14/alpine/entrypoint.sh). Change the `fluent` to `root` 
```sh
#!/usr/bin/dumb-init /bin/sh

uid=${FLUENT_UID:-1000}

# check if a old fluent user exists and delete it
cat /etc/passwd | grep fluent
if [ $? -eq 0 ]; then
    deluser fluent
fi

# (re)add the fluent user with $FLUENT_UID
adduser -D -g '' -u ${uid} -h /home/fluent fluent

# chown home and data folder
chown -R fluent /home/fluent
chown -R fluent /fluentd

exec su-exec root "$@"
```

2. Copy the entrypoint.sh, and replace '/bin/entrypoint.sh'.

```Dockerfile
FROM fluent/fluentd
COPY entrypoint.sh /bin/entrypoint.sh
```

**Comment by jcardoso-bv** [comment]
Why not just set the FLUENT_UID environment variable to 0? Works for us.

**Comment by agasbzj** [comment]
@jcardoso-bv Set FLUENT_UID  works, thank you.

**Comment by sharmmoh1983** [comment]
How to set FLUENT_UID environment variable to 0 and where ?

I am using fluent/fluentd:v0.12.43-debian image in my dockerfile

**Comment by hexinatgithub** [comment]
@jcardoso-bv Set FLUENT_UID works for me, thank you.
I want to tail custom log files in container spec directory, directory host in node like: 
> /var/lib/kubelet/pods/${pid}/volumes/kubernetes.io~empty-dir/${volume_name}/*.log
If I not set FLUENT_UID, fluentd will not tail files in directory and will not report error.
If I set FLUENT_UID=0, every files locate in directory will be tailed.

**Comment by oomichi** [comment]
@jcardoso-bv Thanks, that works for me also.
Why isn't that included in the yaml at the default?
